version: "3.4"

services:
    gitlab-runner:
        image: cr.io/gitlab/gitlab-runner:v16.0.3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:Z
            - ./config:/etc/gitlab-runner:Z
        restart: always
